# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZuc0ddOvxkaVagcs7RvQn7_l5vDPgQP
"""

print("a c e f")

print(7)

print("as variaveis n1 e n2 não foram inicializadas, portanto, a soma não pode ser executava, já que não armazena números")

print(11)

print("o nome da primeira variável esta incorreta,contendo espaços na declaração do nome. A atribuição do valor à variável juros também esta incorreta, já que o nome da variável deve estar á esquerda")

num1 = 3
num2 = 5
num3 = 8
media = (num1 + num2 + num3)/ 3
print(media)

velocidade = 90
velocidade = velocidade / 3.6

print(velocidade)

nome = "Maria"

print("Meu nome é:" ); print(nome)